### ISSUE TITLE
VirtualHost parameter inconsistently defined

### ISSUE THREAD

**Issue by gpduck** [RamblingCookieMonster/RabbitMQTools#1]
The following functions have the VirtualHost parameter set to mandatory and do not provide a default value:
- Add-RabbitMQMessage
- Add-RabbitMQPermission
- Add-RabbitMQQueue
- Add-RabbitMQQueueBinding
- Copy-RabbitMQMessage
- Move-RabbitMQMessage
- Remove-RabbitMQPermission
- Set-RabbitMQPermission

The following functions have the VirtualHost parameter set to mandatory (but do provide a default value):
- Clear-RabbitMQQueue
- Remove-RabbitMQQueueBinding

I feel like optional with default value is the way to go for all of them, but wanted to get feedback before I submit a PR.

**Comment by RamblingCookieMonster** [comment]
Agreed, makes sense to me!

Looking for $defaultVirtualHost, I only see it defined in constants.ps1, which is only called in the tests. Might switch these over to hard coded '/', or setting up a module config of sorts. A variable seems difficult to discover.

**Comment by gpduck** [comment]
Isn't it called in the psm1?

I'm going to update the parameters to use the variable, and later if we add persistent settings that process will just need to update the variable.
