### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by jakauppila** [RamblingCookieMonster/RabbitMQTools#15]
I plan on tackling the last few issues I created. At the same time I'll be looking at the current implementations and refactoring as I go.

I plan on adding tests for as much as I can. This is my first time using Pester, so I have a bit of reading to do.

**Comment by RamblingCookieMonster** [comment]
Awesome! Thanks again for the help. Swing by the Slack PowerShell community ([invite here](http://slack.poshcode.org/)) or powershell.org forums if you run into any trouble.

Tied up with life events, otherwise would use this as a good excuse for mocking / testing practice.

Cheers!

**Comment by jakauppila** [comment]
Feel free to add me to the repo, figured there's at least a couple eyes here rather than maintaining my own fork.

**Comment by RamblingCookieMonster** [comment]
Going to close this out, seems like other issues capture things - cheers!
