### ISSUE TITLE
Missing port number before /api in URLs

### ISSUE THREAD

**Issue by ghost** [RamblingCookieMonster/RabbitMQTools#23]
Default management port is 15672 which should be included in the URLs as in MariuszWojcik's implementation.

**Comment by RamblingCookieMonster** [comment]
Hi there!

This was intentional and one of reasons for the fork (you can see a list of initial changes [here](https://github.com/mariuszwojcik/RabbitMQTools/issues/1)).  Hard coding the port makes it tough for folks who use a different port, for example.

Cheers!

**Comment by ghost** [comment]
Hi, thanks for the clarification.

How should one be using this then for the default case when you do have it on port 15672?

**Comment by ghost** [comment]
Never mind, I'll go with the original implementation from Mariusz.

**Comment by RamblingCookieMonster** [comment]
No problem!

You just include it in the BaseUri parameter:

`-BaseUri "https://rabbitmq.contoso.com:15671"` or `-BaseUri "http://rabbitmq.contoso.com:15672"`, for example.

The SSL bit was important for us, hence the change

Cheers!
