### ISSUE TITLE
IgnoreSslValidation Switch

### ISSUE THREAD

**Issue by austinnichols101** [RamblingCookieMonster/RabbitMQTools#24]
I'm having difficulty establishing an SSL connection to an RMQ that is using a self-signed certificate.  Is there a way to disable SSL validation for troubleshooting purposes?  The following command works:

`$c = New-RabbitMqConnectionFactory -ComputerName 10.1.2.105 -Port 5672 -vhost vhost1 -Credential $CredRabbit -Verbose -Ssl None`

But the following command fails with a Broker error.  Port 5671 AMQPS is confirmed working using TLS 1.2.

`$c = New-RabbitMqConnectionFactory -ComputerName 10.1.2.105 -Port 5671 -vhost vhost1 -Credential $CredRabbit -Verbose -Ssl Tls12`

```
Exception calling "Invoke" with "5" argument(s): "None of the specified endpoints were reachable"
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSRabbitMQ\New-RabbitMqConnectionFactory.ps1:119 char:9
+         $CreateConnectionMethod.Invoke($Factory, "instance,public", $ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : BrokerUnreachableException
```

**Comment by RamblingCookieMonster** [comment]
Hiyo!  Missed this - you might consider [something like this](https://stackoverflow.com/a/15841856/3067642), keeping in mind the duration of that PowerShell session won't validate certs after that.

Closing this out for now, but if you still run into the issue, feel free to re-open

Cheers!
