### ISSUE TITLE
Support for Powershell Core

### ISSUE THREAD

**Issue by mrhockeymonkey** [RamblingCookieMonster/RabbitMQTools#34]
I am currently working on a project whereby I want to run powershell core in containers and query RabbitMQ for work to process. Due to the [changes in Invoke-RestMethod](https://get-powershellblog.blogspot.co.uk/2017/12/powershell-core-web-cmdlets-in-depth_24.html) in powershell core I am at a cross roads. Either I write my own tooling based off of this module or I make the extra effort to support Core and Desktop powershell in this module. 

Would there be any appetite for adding functionality for core to this module? If so I'd be happy to attempt it.

The reason i ask is also that i see [version 1.2 on PSGallery](https://www.powershellgallery.com/packages/RabbitMQTools/1.2) but not in this repo so perhaps im in the wrong place. Please redirect me if so.

**Comment by mrhockeymonkey** [comment]
Turns out this wasn't as hard as i imaged once my coffee kicked in. Have raised PR https://github.com/RamblingCookieMonster/RabbitMQTools/pull/35

Closing this issue

**Comment by RamblingCookieMonster** [comment]
Hiyo!  Yeah this is the gallery bit, we lazily [increment the version automatically](https://github.com/RamblingCookieMonster/RabbitMQTools/blob/master/psake.ps1#L41) so they do mismatch from source

On vacation and won't have much access to a computer, will take a peek at the PR when I get back

Thanks!
